services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - packages/server/env/.env
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    ports:
      - "27017:27017"

  server:
    build:
      dockerfile: packages/server/Dockerfile
    container_name: gryffindor-server
    env_file:
      - packages/server/env/.env
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./packages/server/secret:/mnt/gryffindor/secret
    develop:
      watch:
        - path: .
          action: rebuild

  # client:
  #   build:
  #     dockerfile: packages/client/Dockerfile
  #   container_name: gryffindor-client
  #   env_file:
  #     - packages/client/env/.env
  #   ports:
  #     - "3001:3001"
  #   develop:
  #     watch:
  #       - path: .
  #         action: rebuild

volumes:
  mongo_data:
