export enum ServerPrimaryKeys {
  ME = "ME",
  AGENT = "AGENT",
  AGENT_DETAILS = "AGENT_DETAILS",
  LLM = "LLM",
  KNOWLEDGE_BASE = "KNOWLEDGE_BASE",
  AI_TOOL = "AI_TOOL",
  AGENT_HISTORY = "AGENT_HISTORY",
}
